export type CloudMetric = { id: string; label: string; unit: 'count' | 'usd' | 'percent' | 'position' };
export type CloudSource = { id: string; name: string; group: 'Search' | 'Money' | 'Social' | 'Email' | 'Ads'; provider?: string; resourceLabel?: string; resourcePattern?: string; note: string; metrics: CloudMetric[]; planned?: boolean };
const metric = (id: string, label: string, unit: CloudMetric['unit'] = 'count'): CloudMetric => ({ id, label, unit });
export const CLOUD_SOURCES: CloudSource[] = [
  { id: 'search-console', name: 'Google Search Console', group: 'Search', provider: 'google', resourceLabel: 'Property URL or sc-domain:example.com', resourcePattern: '^(sc-domain:[A-Za-z0-9.-]+|https?://[^\\s]+)$', note: 'Last 28 finalized days, ending three days ago. Search Console reporting is delayed.', metrics: [metric('clicks', 'Search clicks'), metric('impressions', 'Search impressions'), metric('ctr', 'Click-through rate', 'percent'), metric('position', 'Average position', 'position')] },
  { id: 'ga4', name: 'Google Analytics 4', group: 'Search', provider: 'google', resourceLabel: 'GA4 numeric property ID', resourcePattern: '^\\d{1,20}$', note: 'Previous 28 days through yesterday, in the GA4 property timezone.', metrics: [metric('users', 'Active users'), metric('sessions', 'Sessions'), metric('keyEvents', 'Key events')] },
  { id: 'google-business', name: 'Google Business Profile', group: 'Search', provider: 'google-business', resourceLabel: 'Location ID (numbers only)', resourcePattern: '^\\d{1,30}$', note: 'Location call clicks, website clicks and direction requests over the last 28 finalized days. Google requires business.manage, which can allow edits; OmegaOS only reads locations and reports. Separate consent and Google API access approval are required.', metrics: [metric('calls', 'Call clicks'), metric('website', 'Website clicks'), metric('directions', 'Direction requests')] },
  { id: 'stripe', name: 'Stripe', group: 'Money', note: 'Successful USD charges created in the previous 30 days, less refunds recorded against those charges. Not accounting revenue or MRR. Test data is labeled separately.', metrics: [metric('gross', 'USD charges (30 days)', 'usd'), metric('refunded', 'Refunded from those charges', 'usd'), metric('net', 'Charges less refunds', 'usd'), metric('payments', 'Successful USD charges')] },
  { id: 'youtube', name: 'YouTube', group: 'Social', provider: 'google', resourceLabel: 'YouTube channel ID', resourcePattern: '^UC[A-Za-z0-9_-]{22}$', note: 'Channel lifetime totals; hidden subscriber counts remain unknown.', metrics: [metric('subscribers', 'Subscribers'), metric('views', 'Lifetime views'), metric('videos', 'Videos')] },
  { id: 'facebook', name: 'Facebook Page', group: 'Social', provider: 'meta', resourceLabel: 'Facebook Page ID', resourcePattern: '^\\d{1,30}$', note: 'Selected Page follower and like counts. Requires approved Page permissions.', metrics: [metric('followers', 'Followers'), metric('likes', 'Page likes')] },
  { id: 'instagram', name: 'Instagram', group: 'Social', provider: 'meta', resourceLabel: 'Instagram professional account ID', resourcePattern: '^\\d{1,30}$', note: 'Professional account linked to an authorized Facebook Page. Counts only, not personal accounts.', metrics: [metric('followers', 'Followers'), metric('media', 'Published media')] },
  { id: 'meta-ads', name: 'Meta Ads', group: 'Ads', provider: 'meta', resourceLabel: 'Ad account ID (without act_)', resourcePattern: '^\\d{1,30}$', note: 'Last 28 completed days. Spend is shown only for USD ad accounts; other currencies are not converted.', metrics: [metric('spend', 'USD ad spend', 'usd'), metric('impressions', 'Ad impressions'), metric('clicks', 'Ad clicks')] },
  { id: 'tiktok', name: 'TikTok', group: 'Social', provider: 'tiktok', note: 'Authorized account totals. Requires user.info.stats approval.', metrics: [metric('followers', 'Followers'), metric('likes', 'Total likes'), metric('videos', 'Videos')] },
  { id: 'etsy', name: 'Etsy', group: 'Money', provider: 'etsy', resourceLabel: 'Etsy shop ID', resourcePattern: '^\\d{1,30}$', note: 'Shop lifetime sales count and active listings. Revenue, ledger ad spend and per-listing CSV ads are separate follow-up collectors.', metrics: [metric('sales', 'Lifetime sales count'), metric('listings', 'Active listings')] },
  { id: 'email', name: 'Email inbox', group: 'Email', note: 'TLS IMAP INBOX counts only. Google, Microsoft, Yahoo, iCloud and Fastmail supported. No message content is downloaded or sent.', metrics: [metric('messages', 'Inbox messages'), metric('unread', 'Unread messages')] },
  { id: 'linkedin', name: 'LinkedIn', group: 'Social', provider: 'linkedin', resourceLabel: 'Organization ID', resourcePattern: '^\\d{1,30}$', note: 'Organization reporting requires an approved LinkedIn developer app and Community Management access. Personal-profile login alone does not grant Page reporting. Authorization is not enabled.', planned: true, metrics: [metric('followers', 'Organization followers')] },
  { id: 'paypal', name: 'PayPal', group: 'Money', note: 'Merchant reporting setup is not complete. Log in with PayPal identifies an account but does not grant transaction-reporting access. No payment, payout or checkout permissions will be requested.', metrics: [], planned: true },
  { id: 'google-ads', name: 'Google Ads', group: 'Ads', provider: 'google-ads', resourceLabel: 'Customer ID, or manager/customer IDs (10 digits each)', resourcePattern: '^(\\d{10}/)?\\d{10}$', note: 'Previous 28 completed days in the ad account timezone. USD spend only; reported conversions are not revenue. Google requires adwords permission, which permits edits; OmegaOS only reads accounts and reports. Separate consent and API approval are required.', metrics: [metric('spend', 'USD ad spend', 'usd'), metric('impressions', 'Ad impressions'), metric('clicks', 'Ad clicks'), metric('conversions', 'Reported conversions')] },
  { id: 'tiktok-ads', name: 'TikTok Ads', group: 'Ads', note: 'Separate Marketing API approval is required. Collector not enabled in this release.', metrics: [], planned: true },
  { id: 'product-data', name: 'Product and CRM data', group: 'Money', note: 'nosterHealth, custom apps and CRM sources need a reviewed read-only data contract. No production database is connected automatically.', metrics: [], planned: true },
  { id: 'printify', name: 'Printify', group: 'Money', provider: 'printify', resourceLabel: 'Printify shop ID', resourcePattern: '^[1-9]\\d{0,15}$', note: 'Current product count, all-status order count and fulfilled order count for the selected shop. Not sales revenue, profit or a balance; do not add these orders to Shopify or Etsy totals. Read-only shops, products and orders access. No publishing or production actions.', metrics: [metric('products', 'Products'), metric('orders', 'Orders (all statuses)'), metric('fulfilled', 'Fulfilled orders')] },
  { id: 'shopify', name: 'Shopify', group: 'Money', provider: 'shopify', resourceLabel: 'Store domain (your-store.myshopify.com)', resourcePattern: '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.myshopify\\.com$', note: 'Current product count and orders created in the previous 30 days. Exact counts only, not revenue or profit. Read-only products and orders access; no customer details requested, store changes or payments. One authorized store per workspace connection.', metrics: [metric('products', 'Products'), metric('orders', 'Orders (30 days)')] },
];
export function cloudSource(id: string) { const source = CLOUD_SOURCES.find(s => s.id === id); if (!source) throw new Error('Unknown source'); return source; }
export const OAUTH_IDS = ['google', 'google-business', 'google-ads', 'meta', 'tiktok', 'linkedin', 'etsy', 'printify', 'shopify'] as const;
export type OAuthId = typeof OAUTH_IDS[number];
export function oauthId(id: string): OAuthId { if (!(OAUTH_IDS as readonly string[]).includes(id)) throw new Error('Unknown provider'); return id as OAuthId; }
